import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { getLessonsData } from '../lib/lessons';

//const lessons = await getLessonsData();

export async function getStaticProps() {
  const lessons = await getLessonsData();
  return {
    props: {
      lessons
    }
  };
}

export default function Home({ lessons }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Learn Idris</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Siin lehel saad teha algust funktsionaalprogrammeerimise ja -keele Idrisega!
        </h1>

        <div class="grid gap-4 grid-cols-3">
          {lessons.map((lesson, idx) => (
            <Link href={`/lesson/${lesson.id}`}>
              
              <a className="lessonLink" class="bg-sky-100 rounded px-3 hover:bg-sky-200">
                {lesson.title}
              </a>

            </Link>
          ))}
        </div>
       
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
