import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { getLessonsData } from '../lib/lessons';
import { getLessonDataFromLocalStorage } from '../lib/localStorageUtil';

export async function getStaticProps() {
  const lessons = await getLessonsData();
  return {
    props: {
      lessons
    }
  };
}

export default function Home({ lessons }) {
  return (
    <div className={'styles.container bg-[#F6F5F5]'}>
      <Head>
        <title>Learn Idris</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={"title"}>
          Siin lehel saad teha algust funktsionaalprogrammeerimise ja -keele Idrisega!
        </h1>

        <div className={"grid mx-10 gap-5 grid-cols-3"}>
          {lessons.map((lesson, idx) => {
            
            const lessonData = getLessonDataFromLocalStorage(lesson.id);
            const lessonPassed = lessonData !== null ? lessonData.lessonPassed : false;

            return lessonPassed
            ? (
              <Link href={`/lesson/${lesson.id}`} key={idx}>
                
                <a className={"lesson-link"}>
                  {`✓ ${lesson.title}`}
                </a>

              </Link>
            )
            : (
              <Link href={`/lesson/${lesson.id}`} key={idx}>
                
                <a className={"lesson-link"}>
                  {lesson.title}
                </a>

              </Link>
            )
              
          })}
        </div>
       
      </main>
    </div>
  )
}
